export const FETCH_ADMIN_USER_DETAILS_REQUEST = 'FETCH_ADMIN_USER_DETAILS_REQUEST';
export const FETCH_ADMIN_USER_DETAILS_SUCCESS = 'FETCH_ADMIN_USER_DETAILS_SUCCESS';
export const FETCH_ADMIN_USER_DETAILS_FAILURE = 'FETCH_ADMIN_USER_DETAILS_FAILURE';

export const FETCH_ADMIN_USER_API_KEYS_REQUEST = 'FETCH_ADMIN_USER_API_KEYS_REQUEST';
export const FETCH_ADMIN_USER_API_KEYS_SUCCESS = 'FETCH_ADMIN_USER_API_KEYS_SUCCESS';
export const FETCH_ADMIN_USER_API_KEYS_FAILURE = 'FETCH_ADMIN_USER_API_KEYS_FAILURE';

export const GENERATE_ADMIN_USER_API_KEY_REQUEST = 'GENERATE_ADMIN_USER_API_KEY_REQUEST';
export const GENERATE_ADMIN_USER_API_KEY_SUCCESS = 'GENERATE_ADMIN_USER_API_KEY_SUCCESS';
export const GENERATE_ADMIN_USER_API_KEY_FAILURE = 'GENERATE_ADMIN_USER_API_KEY_FAILURE';

export const DELETE_ADMIN_USER_API_KEY_REQUEST = 'DELETE_ADMIN_USER_API_KEY_REQUEST';
export const DELETE_ADMIN_USER_API_KEY_SUCCESS = 'DELETE_ADMIN_USER_API_KEY_SUCCESS';
export const DELETE_ADMIN_USER_API_KEY_FAILURE = 'DELETE_ADMIN_USER_API_KEY_FAILURE';

export const REGENERATE_ADMIN_USER_API_KEY_REQUEST = 'REGENERATE_ADMIN_USER_API_KEY_REQUEST';
export const REGENERATE_ADMIN_USER_API_KEY_SUCCESS = 'REGENERATE_ADMIN_USER_API_KEY_SUCCESS';
export const REGENERATE_ADMIN_USER_API_KEY_FAILURE = 'REGENERATE_ADMIN_USER_API_KEY_FAILURE';
