export const FETCH_ORDERS_REQUEST = 'FETCH_ORDERS_REQUEST';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE';

export const APPROVE_ORDER_REQUEST = 'APPROVE_ORDER_REQUEST';
export const APPROVE_ORDER_SUCCESS = 'APPROVE_ORDER_SUCCESS';
export const APPROVE_ORDER_FAILURE = 'APPROVE_ORDER_FAILURE';

export const REJECT_ORDER_REQUEST = 'REJECT_ORDER_REQUEST';
export const REJECT_ORDER_SUCCESS = 'REJECT_ORDER_SUCCESS';
export const REJECT_ORDER_FAILURE = 'REJECT_ORDER_FAILURE';

export const CLEAR_ORDERS_REQUEST = 'CLEAR_ORDERS_REQUEST';
export const CLEAR_ORDERS_SUCCESS = 'CLEAR_ORDERS_SUCCESS';
export const CLEAR_ORDERS_FAILURE = 'CLEAR_ORDERS_FAILURE';

export const CHECK_ORDER_PAYMENT_REQUEST = 'CHECK_ORDER_PAYMENT_REQUEST';
export const CHECK_ORDER_PAYMENT_SUCCESS = 'CHECK_ORDER_PAYMENT_SUCCESS';
export const CHECK_ORDER_PAYMENT_FAILURE = 'CHECK_ORDER_PAYMENT_FAILURE';

export const DELETE_ORDER_REQUEST = 'DELETE_ORDER_REQUEST';
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS';
export const DELETE_ORDER_FAILURE = 'DELETE_ORDER_FAILURE';
