export const FETCH_SOURCE_INFO_REQUEST = 'FETCH_SOURCE_INFO_REQUEST'
export const FETCH_SOURCE_INFO_SUCCESS = 'FETCH_SOURCE_INFO_SUCCESS'
export const FETCH_SOURCE_INFO_FAILURE = 'FETCH_SOURCE_INFO_FAILURE'

export const CONNECT_TARGET_REQUEST = 'CONNECT_TARGET_REQUEST'
export const CONNECT_TARGET_SUCCESS = 'CONNECT_TARGET_SUCCESS'
export const CONNECT_TARGET_FAILURE = 'CONNECT_TARGET_FAILURE'

export const TRANSFER_DATABASES_REQUEST = 'TRANSFER_DATABASES_REQUEST'
export const TRANSFER_DATABASES_SUCCESS = 'TRANSFER_DATABASES_SUCCESS'
export const TRANSFER_DATABASES_FAILURE = 'TRANSFER_DATABASES_FAILURE'

export const RESET_TRANSFER = 'RESET_TRANSFER'

export const FETCH_TRANSFER_PROGRESS_REQUEST = 'FETCH_TRANSFER_PROGRESS_REQUEST'
export const FETCH_TRANSFER_PROGRESS_SUCCESS = 'FETCH_TRANSFER_PROGRESS_SUCCESS'
export const FETCH_TRANSFER_PROGRESS_FAILURE = 'FETCH_TRANSFER_PROGRESS_FAILURE'
export const STOP_TRANSFER_POLLING = 'STOP_TRANSFER_POLLING'
